### ISSUE TITLE
no_std version?

### ISSUE THREAD

**Issue by mlund** [nadavrot/arpfloat#3]
Would it be possible to have a no_std version? I think many of the `std::` dependencies are available in `core::`. I'm particularly interested in running this on old retro-computers with no fpu.

**Comment by nadavrot** [comment]
Ah, sure. But I've never done this so, I need help. I grepped the code and found the use of "std::cmp::Ordering::Less". Is that okay? I think that the rest of the uses are in unit tests.

**Comment by mlund** [comment]
Great, I will prepared a PR ;-)
